version: "3"
services:
  frontend:
    container_name: frontend_react_app
    restart: always
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: backend_node_app
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
